src/Entity/Planner.php
<?php

namespace App\Entity;

use App\Repository\PlannerRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlannerRepository::class)]
class Planner
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $time_to_eat = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\ManyToOne]
    public ?User $fk_user = null;

    #[ORM\ManyToOne]
    public ?Meals $fk_meal = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTimeToEat(): ?string
    {
        return $this->time_to_eat;
    }

    public function setTimeToEat(string $time_to_eat): static
    {
        $this->time_to_eat = $time_to_eat;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getFkUser(): ?User
    {
        return $this->fk_user;
    }

    public function setFkUser(?User $fk_user): static
    {
        $this->fk_user = $fk_user;

        return $this;
    }

    public function getFkMeal(): ?Meals
    {
        return $this->fk_meal;
    }

    public function setFkMeal(?Meals $fk_meal): static
    {
        $this->fk_meal = $fk_meal;

        return $this;
    }
}

src/Form/PlannerType.php
<?php

namespace App\Form;

use App\Entity\Planner;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PlannerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('time_to_eat', ChoiceType::class, [
                'attr' => ['class' => 'form-control mb-2'],
                'choices'  => [
                    'breakfast' => 1,
                    'lunch' => 2,
                    'dinner' => 3
                ],
            ])
            ->add('date', null, [
                'attr' => ['class' => 'form-control mb-2'],
                'widget' => 'single_text',
            ])
           
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Planner::class,
        ]);
    }
}

src/Controller/PlannerController.php
<?php

namespace App\Controller;

use App\Entity\Planner;
use App\Form\PlannerType;
use App\Repository\PlannerRepository;
use App\Repository\UserRepository;
use App\Repository\MealsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/planner')]
class PlannerController extends AbstractController
{
    #[Route('/', name: 'app_planner_index', methods: ['GET', "POST"])]
    public function index(PlannerRepository $plannerRepository, UserRepository $userRepo, MealsRepository $mealsRepo): Response
    {
        $from= (new \DateTime("first day of this month"))->format("Y-m-d");
        $to = (new \DateTime("last day of this month"))->format("Y-m-d");
        // dd($from, $to);
        if ($_POST){
            $from = $_POST["from"];
            $to =$_POST["to"];
            
        }
        $planner = $plannerRepository->showPlannerForUser($this->getUser()->getId(), "$from", "$to");
      
        
        return $this->render('planner/index.html.twig', [
            'planners' => $planner,
            'users' => $userRepo->findAll(),
            'meals' => $mealsRepo->findAll(),
            'now' => new \DateTime(),
        ]);
    }

    #[Route('/new/{id}', name: 'app_planner_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, $id, MealsRepository $mealsRepository): Response
    {
        $planner = new Planner();
        $form = $this->createForm(PlannerType::class, $planner);
        $form->handleRequest($request);
        $userId = $this->getUser();
        $meal = $mealsRepository->find($id);

        if ($form->isSubmitted() && $form->isValid()) {
            $planner->setFkUser($userId);
            $planner->setFkMeal($meal);
            $entityManager->persist($planner);
            $entityManager->flush();

            return $this->redirectToRoute('app_user_access', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('planner/new.html.twig', [
            'planner' => $planner,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_planner_show', methods: ['GET'])]
    public function show(Planner $planner): Response
    {
        return $this->render('planner/show.html.twig', [
            'planner' => $planner,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_planner_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Planner $planner, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PlannerType::class, $planner);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_planner_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('planner/edit.html.twig', [
            'planner' => $planner,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_planner_delete', methods: ['POST'])]
    public function delete(Request $request, Planner $planner, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$planner->getId(), $request->request->get('_token'))) {
            $entityManager->remove($planner);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_planner_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/planner/_delete_form.html.twig
<form method="post" action="{{ path('app_planner_delete', {'id': planner.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ planner.id) }}">
    <button class="btn btn-primary mt-2">Delete</button>
</form>

templates/planner/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary mb-2 mt-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/planner/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Planner{% endblock %}

{% block body %}
 <div class="container container mb-5 mt-5 border border-3 shadow-lg p-5">
    <h1>Edit Planner</h1>

    {{ include('planner/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-primary" href="{{ path('app_planner_index') }}">back to list</a>

    {{ include('planner/_delete_form.html.twig') }}
 </div>
    
{% endblock %}

templates/planner/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Planner{% endblock %}

{% block body %}

    <div class="container mt-5 mb-4">
        <h1>My Planner</h1>

    <form  action="" method="POST">
        <div class="d-flex  justify-content-between" style="width: 40%;">
            <div style="width: 40%;">
                <input class="form-control" type="date" name="from">
            </div>
            <div style="width: 40%;">
                <input class="form-control" type="date" name="to">  
            </div>
            <div style="width: auto;">
                <button class="btn btn-primary" type="submit">submit</button>
            </div>
        </div>

       
    </form>

    </div>
    <div class="container mb-5  " >
        
    <table class="table shadow-lg border border-5">
        {# <thead>
            <tr>
                <th>Intended Time</th>
                <th>Meal</th>
                <th>Type</th>
                <th>Preperation Time</th>
                <th> </th>
            </tr>
        </thead> #}
        <tbody>
            {% set lastDate = null %}
            
            {% for planner in planners %}

            {% if lastDate == planner.date|date("Y-m-d") %}
            {# <tr class="table-secondary"> #}
                
                <td>
                {# {{ planner.timeToEat }} #}
                {% if planner.timeToEat == "1" %}
                    Breakfast
                {% elseif planner.timeToEat == "2" %}
                    Lunch
                {% elseif planner.timeToEat == "3" %}
                    Dinner
                {% else %}
                    Wrong valuue in database. Must be 1,2 or 3.
                {% endif %}
                
                </td>            
                {% for meal in meals %}
                    {% if meal.id == planner.fkMeal.id %}
                        <td>{{meal.mealName}}</td>
                        <td>{{ meal.mealtype }}</td>
                        <td>{{meal.preparationTime}}</td>
                    
                    {% endif %}
                    
                {% endfor %}
                <td>
                    <a class="btn btn-secondary" href="{{ path('app_meals_show', {'id': planner.fkMeal.id}) }}">show</a>
                    <a class="btn btn-secondary" href="{{ path('app_planner_edit', {'id': planner.id}) }}">edit</a>
                </td>
            </tr>
            
            {% else %}
            {# <tr>
                <td class="table-custom-color" colspan="100"></td>
            </tr> #}
            <tr>
                <td class="table text-light bg-primary fs-4" colspan="100">{{ planner.date|date("l") ~ " " ~ planner.date|date("Y-m-d") }}</td>
            </tr>
            {# <tr class="table-secondary">  #}
                <td>
                {# {{ planner.timeToEat }} #}
                {% if planner.timeToEat == "1" %}
                    Breakfast
                {% elseif planner.timeToEat == "2" %}
                    Lunch
                {% elseif planner.timeToEat == "3" %}
                    Dinner
                {% else %}
                    Wrong value in database. Must be 1,2 or 3.
                {% endif %}
                </td>              
                {% for meal in meals %}
                    {% if meal.id == planner.fkMeal.id %}
                        <td>{{meal.mealName}}</td>
                        <td>{{ meal.mealtype }}</td>
                        <td>{{meal.preparationTime}}</td>
                        
                    {% endif %}
                    
                {% endfor %}
                <td>
                    <a class="btn btn-secondary" href="{{ path('app_meals_show', {'id': planner.fkMeal.id}) }}">show</a>
                    <a class="btn btn-secondary" href="{{ path('app_planner_edit', {'id': planner.id}) }}">edit</a>
                </td>
            </tr>
            
            {% endif %}
            
            {% set lastDate = planner.date|date("Y-m-d") %}

            {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        {# {% for planner in planners %}
        {% if planner.date >= now %}
        
            <tr>
                <td>{{ planner.id }}</td>
                <td>{{ planner.timeToEat }}</td>
                <td>{{ planner.date ? planner.date|date('Y-m-d') : '' }}</td>
                <td>{{ planner.fkUser.email }}</td>
                {% for user in users %}
                    {% if user.id == planner.fkUser.id %}
                        <td>{{user.userName}}</td>
                    {% endif %}
                {% endfor %}
                <td>{{ planner.fkMeal.id }}</td>
                {% for meal in meals %}
                    {% if meal.id == planner.fkMeal.id %}
                        <td>{{meal.mealName}}</td>
                    {% endif %}
                {% endfor %}
                <td>
                    <a href="{{ path('app_planner_show', {'id': planner.id}) }}">show</a>
                    <a href="{{ path('app_planner_edit', {'id': planner.id}) }}">edit</a>
                </td>
            </tr>
            {% endif %}
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %} #}
        </tbody>
    </table>

    {# <a href="{{ path('app_planner_new') }}">Create new</a> #}
    </div>
    
{% endblock %}

{% block stylesheets %}
<style>
    /* table, td, tr, tbody {
        border: none !important;
    }

    .myBorder {
        border: 1px solid grey !important;
    } */

    /* .table-custom-color{
        background: rgb(2,0,36)!important;
background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(0,212,255,1) 75%)!important; 
    } */
</style>
{% endblock %}

templates/planner/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Planner{% endblock %}

{% block body %}
    <div class="container mb-5 mt-5 border border-3 shadow-lg p-5">
        <h1>Add to my Planner</h1>

         {{ include('planner/_form.html.twig') }}

       {% if is_granted("ROLE_ADMIN") %}
        <a class="btn btn-primary" href="{{ path('app_meals_index')}}">back to list</a>
        {% elseif  is_granted("ROLE_USER") %}
         <a class="btn btn-primary" href="{{ path('app_user_access')}}">back to list</a>
        {% else %}
          <h1>There is a problem with access control! contact tech-support...</h1>
        {% endif %}
    </div>

    
{% endblock %}

templates/planner/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Planner{% endblock %}

{% block body %}
    <h1>Planner</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ planner.id }}</td>
            </tr>
            <tr>
                <th>Time_to_eat</th>
                <td>{{ planner.timeToEat }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ planner.date ? planner.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Fk_user</th>
                <td>{{ planner.fkUser }}</td>
            </tr>
            <tr>
                <th>Fk_meal</th>
                <td>{{ planner.fkMeal }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_planner_index') }}">back to list</a>

    <a href="{{ path('app_planner_edit', {'id': planner.id}) }}">edit</a>

    {{ include('planner/_delete_form.html.twig') }}
{% endblock %}